spring:
  datasource:
    url: jdbc:h2:mem:qs;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:12345
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: ChangeMeToAStrongSecret
  expiration-ms: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
